# Generated by Django 2.2.4 on 2020-08-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Show',
        ),
    ]
